<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/datatables/dataTables.bootstrap4.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.foundation.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.jqueryui.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.material.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.semanticui.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/dataTables.uikit.min.css'))
            //->prependStylesheet($this->basePath('css/datatables/jquery.dataTables_themeroller.css'))
            ->prependStylesheet($this->basePath('css/datatables/jquery.dataTables.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/datatables/jquery.dataTables.min.js'))
            //->prependFile('https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js')
            //->prependFile('https://code.jquery.com/jquery-1.12.4.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/datatables/jquery.js'))
            //->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.bootstrap.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.bootstrap4.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.foundation.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.jqueryui.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.material.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.semanticui.min.js'))
            //->prependFile($this->basePath('js/datatables/dataTables.uikit.min.js'))
            
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li><a href="<?= $this->url('album') ?>">Album</a>
                            <!--
                            <ul id="jq-espace_travail" class="nav nav-second-level nav-workspace-level">
                                <li><a href="<?= $this->url('album') ?>">Ajouter</a></li>
                            </ul>
                            -->
                        </li>
                        <li><a href="<?= $this->url('listes') ?>">Listes</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            Site tuto ZF3 : <a href="https://docs.zendframework.com/tutorials/getting-started/forms-and-actions/">https://docs.zendframework.com/tutorials/getting-started/forms-and-actions/</a><br>
            Menu : voir identique sur WTG<br>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
